book_structures = [
    {"name": "Fact sheet", "type": "Non-fiction", "age": [4, 5], "instruction": "Create a concise, bullet-pointed list of key facts on a specific topic. Organize the facts in a logical sequence, using simple language and clear, direct statements. Use headings to categorize the information if needed."},
    {"name": "Timeline", "type": "Non-fiction", "age": [4, 5], "instruction": "Structure the content chronologically, starting with the earliest events and progressing to the most recent. Include dates and brief descriptions for each event, using a linear flow that emphasizes the sequence of occurrences."},
    {"name": "Categorical", "type": "Non-fiction", "age": [4, 5], "instruction": "Organize information into distinct categories or groups. Each category should have a clear heading, with relevant details or examples listed underneath. Use a consistent format to present information within each category."},
    {"name": "Question and Answer", "type": "Non-fiction", "age": [3, 4, 5], "instruction": "Pose a series of relevant questions related to the topic and provide clear, concise answers. Use the question as a heading or introduction to each section, followed by a straightforward answer in simple language."},
    {"name": "Step-by-Step", "type": "Non-fiction", "age": [3, 4, 5], "instruction": "Break down a process into individual steps. Each step should be clearly numbered and described in a logical order. Use imperative sentences or direct instructions to guide the reader through the process."},
    {"name": "Problem-Solution", "type": "Non-fiction", "age": [4, 5], "instruction": "Present a problem or challenge at the beginning of each section, followed by a clear explanation or solution. Structure the content to highlight how the solution addresses the problem effectively."},
    {"name": "Compare and Contrast", "type": "Non-fiction", "age": [4, 5], "instruction": "Identify two or more items, concepts, or ideas to compare and contrast. Highlight their similarities and differences using a clear, organized format. Include headings or subheadings for each aspect being compared."},
    {"name": "Cause and Effect", "type": "Non-fiction", "age": [4, 5], "instruction": "Explain the relationship between an action (cause) and its outcome (effect). Organize the content by first detailing the cause, then describing the effect, ensuring a logical connection is clearly established."},
    {"name": "Alphabetical", "type": "Non-fiction", "age": [3, 4, 5], "instruction": "Organize information alphabetically, with each section or entry corresponding to a letter of the alphabet. Use clear headings or titles for each entry, ensuring the structure remains consistent throughout."},
    {"name": "Descriptive", "type": "Non-fiction", "age": [3, 4, 5], "instruction": "Focus on providing detailed descriptions of a topic. Use vivid language and sensory details to create a clear, immersive picture. Organize the content by subtopics or features, ensuring a cohesive flow of information."},
    {"name": "How-to", "type": "Non-fiction", "age": [4, 5], "instruction": "Provide instructions on how to perform a task or activity. Organize the content into clear, numbered steps, with each step including a simple, direct command or explanation. Include tips or warnings as necessary."},
    {"name": "List", "type": "Non-fiction", "age": [3, 4, 5], "instruction": "Present information in a straightforward list format. Use bullet points or numbers to organize the content, ensuring each item in the list is brief and to the point. Group related items together for clarity."},
    {"name": "Fact vs Myth", "type": "Non-fiction", "age": [4, 5], "instruction": "Present common myths or misconceptions alongside factual information. Use a side-by-side format, clearly labeling each section as 'Myth' or 'Fact.' Provide simple explanations for why each myth is incorrect."},
    {"name": "Dialogue", "type": "Non-fiction", "age": [4, 5], "instruction": "Structure the content as a conversation between two or more characters. Use direct speech to convey information, with each character contributing to the discussion in a natural, engaging way."},
    {"name": "Counting", "type": "Non-fiction", "age": [2, 3, 4], "instruction": "Focus on teaching counting through repetition and sequence. Present numbers in a linear order, using simple examples or scenarios that clearly illustrate the concept of counting. Include visual or textual representations."},
    {"name": "Multi-Sensory", "type": "Non-fiction", "age": [0, 1, 2, 3, 4, 5], "instruction": "Engage multiple senses by describing the topic using sensory language. Include visual, auditory, tactile, and other sensory details. Structure the content to move through different senses systematically or contextually."},
    {"name": "Zoom-in", "type": "Non-fiction", "age": [4, 5], "instruction": "Start with a broad overview of the topic and progressively focus on smaller, more detailed aspects. Structure the content to guide the reader from general to specific, with each section narrowing in scope."},
    {"name": "Zoom-out", "type": "Non-fiction", "age": [4, 5], "instruction": "Begin with detailed, specific information and gradually expand to a broader context. Organize the content to move from small details to a larger perspective, highlighting how each part fits into the whole."},
    {"name": "Rhyming", "type": "Non-fiction", "age": [0, 1, 2, 3, 4, 5], "instruction": "Write the content in a rhyming, poetic structure. Ensure that each line or section rhymes with the next, using simple, rhythmic language. Maintain a consistent rhyme scheme throughout the book."},
    {"name": "Sequential", "type": "Non-fiction", "age": [3, 4, 5], "instruction": "Present the information in a logical, step-by-step order. Each section should naturally lead to the next, ensuring a clear progression from beginning to end. Use transitional phrases to maintain flow."},
    {"name": "Simple Narrative Structure", "type": "Fiction", "age": [2, 3, 4, 5], "instruction": "Tell a straightforward story with a clear beginning, middle, and end, suitable for young children."},
    {"name": "Cumulative Structure", "type": "Fiction", "age": [2, 3, 4, 5], "instruction": "Add a new element in each sentence, building up the scenario step by step without a traditional climax."},
    {"name": "Rhyming Structure", "type": "Fiction", "age": [0, 1, 2, 3, 4, 5], "instruction": "Create a story where each sentence ends in a rhyme, focusing on rhythm and sound over plot development."},
    {"name": "Repetitive Structure", "type": "Fiction", "age": [0, 1, 2, 3, 4, 5], "instruction": "Use repetition throughout the story to reinforce key ideas, avoiding a traditional plot progression."},
    {"name": "Circular Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Start and end the story in the same place."},
    {"name": "Quest Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Describe a character's journey with small adventures, but avoid a final resolution or traditional climax."},
    {"name": "Character-Centric Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Focus on a character's personality and actions without necessarily driving towards a climactic event."},
    {"name": "Parallel Structure", "type": "Fiction", "age": [4, 5], "instruction": "Create two parallel storylines that mirror each other, which lead to convergence into a single climax."},
    {"name": "Problem and Solution Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Present a problem and show how it is resolved."},
    {"name": "In Media Res Structure", "type": "Fiction", "age": [4, 5], "instruction": "Begin the story in the middle of the action."},
    {"name": "Dialogue-Driven Structure", "type": "Fiction", "age": [4, 5], "instruction": "Focus on character dialogue to drive the story."},
    {"name": "Multiple Perspectives Structure", "type": "Fiction", "age": [4, 5], "instruction": "Narrate the story from different characters' perspectives."},
    {"name": "Predictable Pattern Structure", "type": "Fiction", "age": [2, 3, 4], "instruction": "Create a story with a repeating, predictable pattern, avoiding traditional story progression."},
    {"name": "Interactive Structure", "type": "Fiction", "age": [2, 3, 4, 5], "instruction": "The plot should include key moments that interact with the reader via prompts and questions."},
    {"name": "Transformation Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Show how a character or situation changes over time."},
    {"name": "Mystery Structure", "type": "Fiction", "age": [4, 5], "instruction": "Present a simple mystery with clues."},
    {"name": "Day-in-the-Life Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Describe a typical day in the life of a character, focusing on routine rather than an exciting plot."},
    {"name": "Opposites Structure", "type": "Fiction", "age": [2, 3, 4], "instruction": "Use contrasting ideas or characters, emphasizing differences without progressing to a traditional story arc."},
    {"name": "Object-Centric Structure", "type": "Fiction", "age": [2, 3, 4], "instruction": "Focus the story around an object, describing its use or significance, without developing a traditional plot."},
    {"name": "Wish Fulfillment Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Center the story around a character's wish, showing it being granted."},
    {"name": "Alphabet Story Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Create a story that follows the alphabet, introducing a new element with each letter, keeping it simple and non-climactic."},
    {"name": "Fantasy Structure", "type": "Fiction", "age": [4, 5], "instruction": "Describe a magical world or event, focusing on wonder rather than plot development."},
    {"name": "Twist Ending Structure", "type": "Fiction", "age": [4, 5], "instruction": "Introduce an unexpected twist which is humorous or joyful at the end."},
    {"name": "Lullaby Structure", "type": "Fiction", "age": [0, 1, 2], "instruction": "Use soothing, repetitive language and rhythm, without a traditional plot, to create a calming effect."},
    {"name": "Personification Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Give human traits to objects or animals, focusing on their actions rather than a central plot."},
    {"name": "Family-Centric Structure", "type": "Fiction", "age": [2, 3, 4, 5], "instruction": "Describe a family situation or interaction, keeping the story simple and relatable to the everyday lives of children."},
    {"name": "Exploration and Discovery Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Describe a character exploring a new place, focusing on discovery rather than building to a climax."},
    {"name": "Contrasting Worlds Structure", "type": "Fiction", "age": [4, 5], "instruction": "Describe two contrasting worlds or realities."},
    {"name": "Rhythmic and Musical Structure", "type": "Fiction", "age": [0, 1, 2, 3], "instruction": "Use rhythm and musical elements in the language to create a playful and engaging story, without a plot."},
    {"name": "Tall Tale Structure", "type": "Fiction", "age": [4, 5], "instruction": "Tell an exaggerated, humorous story, focusing on the absurdity rather than following a traditional plot."},
    {"name": "Imaginative Play Structure", "type": "Fiction", "age": [2, 3, 4, 5], "instruction": "Describe a scenario of imaginative play, keeping the story open-ended and free-flowing."},
    {"name": "Sequence of Events Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Describe events in a logical sequence, focusing on the order of actions rather than developing a plot."},
    {"name": "Magic and Wonder Structure", "type": "Fiction", "age": [3, 4, 5], "instruction": "Create a story filled with magical elements, focusing on the sense of wonder rather than a traditional plot."},
    {"name": "Allegory", "type": "Fiction", "age": [4, 5], "instruction": "Use characters or events to symbolize abstract ideas, ensuring the story remains understandable for young children."},
    {"name": "Chekhov's Gun", "type": "Fiction", "age": [4, 5], "instruction": "Introduce elements early in the story that are used later, but keep the plot straightforward and accessible."},
    {"name": "Deus Ex Machina", "type": "Fiction", "age": [4, 5], "instruction": "Resolve the story with an unexpected intervention."},
    {"name": "Flashback", "type": "Fiction", "age": [4, 5], "instruction": "Incorporate brief scenes from the past to provide context, making sure it integrates smoothly."},
    {"name": "Foreshadowing", "type": "Fiction", "age": [4, 5], "instruction": "Hint at future events in a way that is clear and straightforward, avoiding complex or subtle clues."},
    {"name": "Frame Story", "type": "Fiction", "age": [4, 5], "instruction": "Use a story within a story, keeping the framing simple and integrate it smoothly."},
    {"name": "Motif", "type": "Fiction", "age": [4, 5], "instruction": "Repeatedly use a specific theme or element throughout the story, ensuring it enhances the narrative."},
    {"name": "Yarn", "type": "Fiction", "age": [4, 5], "instruction": "Tell a long, engaging story with entertaining details."}
]

number_of_main_characters = [
    {"name": "1", "age": [0, 1, 2, 3, 4, 5]},
    {"name": "2", "age": [2, 3, 4, 5]},
    {"name": "3", "age": [4, 5]}
]

number_of_total_characters = [
    {"name": "1-2", "age": [0, 1, 2, 3, 4, 5]},
    {"name": "2-3", "age": [2, 3, 4, 5]},
    {"name": "3-4", "age": [3, 4, 5]},
    {"name": "4-5", "age": [4, 5]},
    {"name": "5-7", "age": [5]}
]

narrative_perspectives = [
    {"name": "First person", "type": ["Fiction", "Non-fiction"]},
    {"name": "Second person", "type": ["Fiction", "Non-fiction"]},
    {"name": "Third person limited", "type": ["Fiction"]},
    {"name": "Third person omniscient", "type": ["Fiction", "Non-fiction"]}
]

writing_styles = [
    {"name": "Childish", "age": [0, 1, 2, 3, 4, 5], "instruction": "Use simple, clear language with straightforward sentences. Focus on familiar concepts and sensory experiences."},
    {"name": "Conversational", "age": [3, 4, 5], "instruction": "Use a friendly, informal tone as if speaking directly to the reader. Include direct questions and relatable scenarios."},
    {"name": "Epistolary", "age": [5], "instruction": "Frame the narrative as a series of letters or messages. Use personal, reflective language. Ensure the format is simple and accessible for early readers."},
    {"name": "Journalistic", "age": [5], "instruction": "Present information clearly and concisely, similar to a news report. Focus on factual content with simple, straightforward language."},
    {"name": "Lyrical", "age": [4, 5], "instruction": "Use rhythmic, melodic language with a poetic quality. Incorporate repetition and patterns to engage the reader."},
    {"name": "Philosophical", "age": [5], "instruction": "Introduce simple moral or existential questions in a way that is easy to understand. Use gentle, thought-provoking language."},
    {"name": "Poetic", "age": [4, 5], "instruction": "Employ rhyme, rhythm, and vivid imagery. Use lyrical language to evoke emotions and create a musical quality."},
    {"name": "Sparse", "age": [3, 4, 5], "instruction": "Use minimal text. Keep language simple and direct."},
    {"name": "Stream-of-Consciousness", "age": [5], "instruction": "Present thoughts and feelings in a flowing, unstructured manner. Use simple sentences and fragments to mimic natural thought processes."},
    {"name": "Whimsical", "age": [3, 4, 5], "instruction": "Use playful, imaginative language with unexpected, fanciful elements. Include humorous or surreal scenarios."}
]

sentence_structures = [
    {"name": "Simple Sentence", "age": [0, 1, 2, 3, 4, 5], "example": "The cat sleeps.", "language": "English"},
    {"name": "Compound Sentence", "age": [4, 5], "example": "She wanted to go to the park, but it was raining, so she stayed indoors.", "language": "English"},
    {"name": "Complex Sentence", "age": [4, 5], "example": "Though it was raining, she decided to go to the park.", "language": "English"},
    {"name": "Declarative Sentence", "age": [0, 1, 2, 3, 4, 5], "example": "The dog is big.", "language": "English"},
    {"name": "Exclamatory phrase", "age": [0, 1, 2, 3, 4, 5], "example": "Wow, that’s an amazing view!", "language": "English"},
    {"name": "Interjection", "age": [2, 3, 4, 5], "example": "Oh, I didn’t see you there!", "language": "English"},
    {"name": "Simple Compound Sentence", "age": [3, 4, 5], "example": "He went to the store, and she stayed home.", "language": "English"},
    {"name": "Simple subject and predicate", "age": [0, 1, 2, 3, 4, 5], "example": "The cat slept.", "language": "English"},
    {"name": "Imperative Sentence", "age": [2, 3, 4, 5], "example": "Please close the book.", "language": "English"},
    {"name": "Comparative Sentence", "age": [3, 4, 5], "example": "The apple is bigger than the orange.", "language": "English"},
    {"name": "Superlative Sentence", "age": [3, 4, 5], "example": "This is the tallest building.", "language": "English"},
    {"name": "Simile", "age": [3, 4, 5], "example": "The kitten is as soft as a cloud.", "language": "English"},
    {"name": "Metaphor", "age": [4, 5], "example": "The night sky is a velvet blanket.", "language": "English"},
    {"name": "Onomatopoeia", "age": [1, 2, 3, 4, 5], "example": "The clock goes tick-tock.", "language": "English"},
    {"name": "Parallelism", "age": [3, 4, 5], "example": "She likes running, swimming, and biking.", "language": "English"},
    {"name": "Modal Verbs", "age": [4, 5], "example": "Can you help me?", "language": "English"},
    {"name": "Passive Voice", "age": [5], "example": "The cake was eaten by the children.", "language": "English"},
    {"name": "Cumulative Sentence", "age": [4, 5], "example": "The house was big and old and had a red door.", "language": "English"},
    {"name": "Conditional Sentence", "age": [3, 4, 5], "example": "If it rains, we will stay inside.", "language": "English"},
    {"name": "Relative Pronoun", "age": [4, 5], "example": "The book that I read is exciting.", "language": "English"},
    {"name": "Quantitative Description", "age": [3, 4, 5], "example": "I have three blue balls.", "language": "English"},
    {"name": "Direct and Indirect Object", "age": [3, 4, 5], "example": "She gave him the book.", "language": "English"},
    {"name": "Appositive Phrase", "age": [4, 5], "example": "My friend, the doctor, is visiting.", "language": "English"},
    {"name": "Absolute Phrase", "age": [4, 5], "example": "Her homework finished, she went out to play.", "language": "English"},
    {"name": "Adverbial clause", "age": [3, 4, 5], "example": "She danced beautifully because she had practiced for weeks.", "language": "English"},
    {"name": "Adverbial phrase", "age": [4, 5], "example": "With great enthusiasm, she accepted the challenge.", "language": "English"},
    {"name": "Anadiplosis", "age": [5], "example": "Strength through purity, purity through faith.", "language": "English"},
    {"name": "Anaphora", "age": [5], "example": "I have a dream... I have a dream...", "language": "English"},
    {"name": "Antithesis", "age": [5], "example": "It was the best of times, it was the worst of times.", "language": "English"},
    {"name": "Appositive Clause", "age": [4, 5], "example": "My dog, who loves to play fetch, is very energetic.", "language": "English"},
    {"name": "Assonance", "age": [2, 3, 4, 5], "example": "The rain in Spain stays mainly in the plain.", "language": "English"},
    {"name": "Chiasmus", "age": [5], "example": "Ask not what your country can do for you, but what you can do for your country.", "language": "English"},
    {"name": "Clause of reason or purpose", "age": [3, 4, 5], "example": "He went to bed early so that he would be rested for the meeting.", "language": "English"},
    {"name": "Comment on the preceding statement", "age": [5], "example": "That was quite an interesting lecture. I learned a lot about ancient history.", "language": "English"},
    {"name": "Comparison", "age": [3, 4, 5], "example": "Her performance was better than I expected.", "language": "English"},
    {"name": "Complex-Compound Sentence", "age": [5], "example": "Though it was raining, the event was held outdoors, and everyone enjoyed it.", "language": "English"},
    {"name": "Compound subject", "age": [3, 4, 5], "example": "My sister and I went to the concert.", "language": "English"},
    {"name": "Conditional clause", "age": [3, 4, 5], "example": "If it rains tomorrow, we will stay indoors.", "language": "English"},
    {"name": "Contrastive conjunction", "age": [5], "example": "I wanted to go; however, I had too much work.", "language": "English"},
    {"name": "Direct address", "age": [0, 1, 2, 3, 4, 5], "example": "John, could you please help me with this?", "language": "English"},
    {"name": "Direct quotation", "age": [4, 5], "example": "‘To be, or not to be, that is the question,’ said Shakespeare.", "language": "English"},
    {"name": "Elliptical Clause", "age": [5], "example": "She can play the piano; he, the guitar.", "language": "English"},
    {"name": "Epanalepsis", "age": [5], "example": "The king is dead, long live the king!", "language": "English"},
    {"name": "Epiphora", "age": [5], "example": "I want pizza; she wants pizza; we all want pizza.", "language": "English"},
    {"name": "Focus construction", "age": [5], "example": "It was the sudden change in weather that surprised everyone.", "language": "English"},
    {"name": "Gerund phrase", "age": [3, 4, 5], "example": "Swimming in the ocean is her favorite activity.", "language": "English"},
    {"name": "Hyperbaton", "age": [5], "example": "Object there was none. Passion there was none.", "language": "English"},
    {"name": "Imperative verb", "age": [2, 3, 4, 5], "example": "Please close the door.", "language": "English"},
    {"name": "Infinitive phrase", "age": [4, 5], "example": "To finish the project on time, he worked late into the night.", "language": "English"},
    {"name": "Introductory clause", "age": [4, 5], "example": "Although it was raining, we decided to go for a walk.", "language": "English"},
    {"name": "Introductory Participle Phrase", "age": [4, 5], "example": "Hoping for a better outcome, she studied harder for the test.", "language": "English"},
    {"name": "Inverted Sentence", "age": [5], "example": "Under the bridge ran a swift stream.", "language": "English"},
    {"name": "Isocolon", "age": [5], "example": "Veni, vidi, vici.", "language": "English"},
    {"name": "Negative Sentence", "age": [3, 4, 5], "example": "He does not like spicy food.", "language": "English"},
    {"name": "Noun clause", "age": [4, 5], "example": "What she decided was surprising to everyone.", "language": "English"},
    {"name": "Noun modifier", "age": [4, 5], "example": "The swimming pool was closed for maintenance.", "language": "English"},
    {"name": "Parallel Structure", "age": [5], "example": "She enjoys reading, writing, and painting.", "language": "English"},
    {"name": "Participial phrase", "age": [4, 5], "example": "Running through the park, she enjoyed the fresh air.", "language": "English"},
    {"name": "Periodic Sentence", "age": [5], "example": "Despite the rain and wind, the team finished the race, and their spirits were high.", "language": "English"},
    {"name": "Polyptoton", "age": [5], "example": "With eager and with eagerness.", "language": "English"},
    {"name": "Prepositional phrase", "age": [3, 4, 5], "example": "Under the old oak tree, the children played happily.", "language": "English"},
    {"name": "Prepositional phrase for emphasis", "age": [4, 5], "example": "In the middle of the night, the house was eerily quiet.", "language": "English"},
    {"name": "Quantifier", "age": [3, 4, 5], "example": "Many students were absent from class today.", "language": "English"},
    {"name": "Question", "age": [3, 4, 5], "example": "What time does the meeting start?", "language": "English"},
    {"name": "Relative clause", "age": [3, 4, 5], "example": "The book that she borrowed was very interesting.", "language": "English"},
    {"name": "Repetition", "age": [0, 1, 2, 3, 4, 5], "example": "The city was bustling, bustling with life.", "language": "English"},
    {"name": "Result clause", "age": [3, 4, 5], "example": "She studied hard, so she passed the exam with flying colors.", "language": "English"},
    {"name": "Syntactic Parallelism", "age": [5], "example": "To err is human; to forgive, divine.", "language": "English"},
    {"name": "Tautology", "age": [5], "example": "Free gift.", "language": "English"},
    {"name": "Transitional word or phrase", "age": [4, 5], "example": "However, we still managed to finish on time.", "language": "English"},
    {"name": "Tricolon", "age": [5], "example": "I came, I saw, I conquered.", "language": "English"},
    {"name": "Verbless sentence (ellipsis)", "age": [5], "example": "I like apples; she, oranges.", "language": "English"},
    {"name": "Apostrophe", "age": [4, 5], "example": "Dear Moon, can you please tell me why you follow me everywhere I go?", "language": "English"},
    {"name": "Accismus", "age": [5], "example": "Oh, I don’t want any cake; it’s not like I have a sweet tooth or anything.", "language": "English"},
    {"name": "Alliteration", "age": [0, 1, 2, 3, 4, 5], "example": "Peter Piper picked a peck of pickled peppers.", "language": "English"},
    {"name": "Allusion", "age": [5], "example": "He met his Waterloo.", "language": "English"},
    {"name": "Brevity", "age": [4, 5], "example": "Less is more.", "language": "English"},
    {"name": "Conceit", "age": [5], "example": "Love is like a rose, with thorns and all.", "language": "English"},
    {"name": "Connotation", "age": [5], "example": "Home implies warmth and safety.", "language": "English"},
    {"name": "Diacope", "age": [5], "example": "To be, or not to be.", "language": "English"},
    {"name": "Elegy", "age": [5], "example": "O Captain! My Captain!", "language": "English"},
    {"name": "Enjambment", "age": [5], "example": "The sun rising on the horizon, its light spreading...", "language": "English"},
    {"name": "Epanorthosis", "age": [5], "example": "He was the best actor in the world—or at least in our town.", "language": "English"},
    {"name": "Epigram", "age": [5], "example": "I can resist everything except temptation.", "language": "English"},
    {"name": "Euphemism", "age": [5], "example": "He passed away (instead of 'he died').", "language": "English"},
    {"name": "Exaggeration", "age": [4, 5], "example": "I’ve told you a thousand times.", "language": "English"},
    {"name": "Hendiadys", "age": [5], "example": "Nice and warm (instead of 'warmth').", "language": "English"},
    {"name": "Hyperbole", "age": [4, 5], "example": "I’ve told you a million times.", "language": "English"},
    {"name": "Hypophora", "age": [5], "example": "What should we do? We should act now.", "language": "English"},
    {"name": "Iambic Pentameter", "age": [5], "example": "Shall I compare thee to a summer’s day?", "language": "English"},
    {"name": "Imagery", "age": [4, 5], "example": "The golden sun dipped below the horizon.", "language": "English"},
    {"name": "Irony", "age": [5], "example": "The fire station burned down.", "language": "English"},
    {"name": "Litotes", "age": [5], "example": "She’s not unattractive.", "language": "English"},
    {"name": "Metalepsis", "age": [5], "example": "He’s gone to a better place (implies death).", "language": "English"},
    {"name": "Metonymy", "age": [5], "example": "The White House announced new policies.", "language": "English"},
    {"name": "Oxymoron", "age": [5], "example": "Bittersweet.", "language": "English"},
    {"name": "Paradox", "age": [5], "example": "Less is more.", "language": "English"},
    {"name": "Periphrasis", "age": [5], "example": "The father of my father (instead of 'grandfather').", "language": "English"},
    {"name": "Pleonasm", "age": [2, 3, 4, 5], "example": "I saw it with my own eyes.", "language": "English"},
    {"name": "Portmanteau", "age": [4, 5], "example": "Brunch (breakfast + lunch).", "language": "English"},
    {"name": "Repetition", "age": [2, 3, 4, 5], "example": "I have a dream...", "language": "English"},
    {"name": "Rhetorical Question", "age": [3, 4, 5], "example": "Isn’t it obvious?", "language": "English"},
    {"name": "Rhyme", "age": [2, 3, 4, 5], "example": "The cat in the hat.", "language": "English"},
    {"name": "Sibilance", "age": [2, 3, 4, 5], "example": "She sells seashells by the seashore.", "language": "English"},
    {"name": "Simile", "age": [3, 4, 5], "example": "As brave as a lion.", "language": "English"},
    {"name": "Synecdoche", "age": [5], "example": "All hands on deck.", "language": "English"},
    {"name": "Understatement", "age": [5], "example": "It’s just a scratch for a deep wound.", "language": "English"},
    {"name": "Zeugma", "age": [5], "example": "He stole my heart and my wallet.", "language": "English"}
]

book_lengths = [
    {"name": "8-12", "age": [0]},
    {"name": "10-16", "age": [1]},
    {"name": "12-20", "age": [2]},
    {"name": "20-32", "age": [3]},
    {"name": "32-40", "age": [4]},
    {"name": "40-60", "age": [5]}
]

words_per_page = [
    {"name": "0-10", "age": [0]},
    {"name": "10-20", "age": [1]},
    {"name": "20-30", "age": [2]},
    {"name": "30-50", "age": [3]},
    {"name": "50-70", "age": [4]},
    {"name": "70-100", "age": [5]}
]

age_instructions = [
    {"type": "Scientific knowledge", "age": [3], "instruction": "Stick to observable phenomena and direct experiences. Focus on sensory experiences—what they can see, hear, touch, taste, or smell. Relate scientific ideas to familiar objects and activities, like animals, colors, shapes, or weather."},
    {"type": "Scientific knowledge", "age": [4], "instruction": "Include the concept of 'why' and 'how' things happen. Reinforce ideas by repeating key concepts in different ways. Use simple analogies to closely relate scientific knowledge to the child’s everyday experiences."},
    {"type": "Scientific knowledge", "age": [5], "instruction": "Introduce abstract ideas which are still rooted in observable phenomena. Explain how things can be grouped or compared. Explanations of scientific phenomena can include a sequence of events."},
    {"type": "Scientific knowledge", "age": [0], "instruction": "Focus on sensory experiences: sights, sounds, textures, and simple patterns. Use simple, repetitive and rhythmic language. No abstract concepts."},
    {"type": "Scientific knowledge", "age": [1], "instruction": "Focus on simple concepts related to the child's immediate environment, like objects they can touch, see, and interact with. Use simple, descriptive words that connect to their sensory experiences. Introduce very basic cause and effect in the most straightforward ways."},
    {"type": "Scientific knowledge", "age": [2], "instruction": "Introduce basic comparisons and very simple categorization. Encourage naming and labeling. Use simple, relatable examples to common experiences in their daily life. Extremely simple explanations of why things happen."},
    {"type": "Vocabulary", "age": [0], "instruction": "Focus on phonemic awareness: Utilize simple, repetitive phonemes and onomatopoeic words that emphasize sound patterns. Employ single-syllable words with high phonological clarity, focusing on auditory stimuli rather than meaning. Integrate rhythmic patterns and intonational contours to engage auditory perception. Use words with minimal semantic complexity, relying more on the prosodic and rhythmic qualities of language. Use the present simple tense."},
    {"type": "Vocabulary", "age": [1], "instruction": "Use simple adjectives, descriptive nouns, and basic action verbs. Use concrete nouns and primary verbs that refer to objects and actions within the immediate environment of a very young child. Support the use of single-word utterances (holophrases) to convey entire ideas or requests. Select words that are perceptually prominent, with clear phonological structure and high frequency in infant-directed speech. Encourage the use of reduplicative forms, which are common in early word production and facilitate phonological processing. Incorporate basic cause-and-effect language related to everyday objects and actions to support early cognitive development. Use the present simple tense."},
    {"type": "Vocabulary", "age": [2], "instruction": "Utilize emerging vocabulary with a focus on basic categorization and simple relational words. Utilize vocabulary that aligns with telegraphic speech patterns, consisting mainly of content words (nouns, verbs) with minimal use of function words (articles, prepositions). Maintain a focus on concrete, tangible concepts, avoiding abstract or figurative language. Include basic comparative adjectives (e.g., 'big vs. small') and simple prepositions (e.g., 'in,' 'on'). Encourage early conceptual understanding through simple comparisons. Introduce simple morphological inflections, such as plurals and present continuous (-ing) forms. Incorporate basic descriptive adjectives to expand vocabulary and encourage adjectival modification. Use the present simple tense."},
    {"type": "Vocabulary", "age": [3], "instruction": "Use vocabulary that supports simple sentence construction, with an emphasis on subject-verb-object (SVO) syntax. Introduce basic categories and classifications, that group similar objects or actions. Introduce simple function words (e.g., prepositions, conjunctions). Concrete and Familiar Concepts: Focus on vocabulary related to everyday experiences and familiar routines in early childhood. Incorporate simple narrative structures and cause-and-effect language with basic storyline elements. Use mainly present tense and incorporate some simple past tense."},
    {"type": "Vocabulary", "age": [4], "instruction": "Introduce simple figurative language (e.g., similes, basic metaphors) in a highly concrete context. Encourage the use of a broader range of adjectives, adverbs, and more complex nouns and verbs. Integrate expanded descriptive language with basic narrative elements and early abstract concepts. Use vocabulary that allows for the exploration of more complex morphosyntactic structures, such as compound sentences and basic past tense forms.  Introduce vocabulary that supports simple narrative structure, including temporal markers (e.g., 'first,' 'then') and causal connectors (e.g., 'because'). Use both present and simple past tenses."},
    {"type": "Vocabulary", "age": [5], "instruction": "Incorporate rich descriptive vocabulary containing abstract nouns and verbs, simple metaphors, and complex sentence structures. Use vocabulary to support more complex narratives, including varied temporal and causal structures, descriptive sequences, and dialogue. Introduce basic concepts that go beyond the immediate physical environment. Employ basic plot elements and narrative techniques to support early inference skills and detailed storytelling. Introduce simple idioms or colloquial expressions, ensuring they are explained within context. Use vocabulary that allows for the introduction of basic literary devices such as alliteration, repetition for emphasis, and simple analogies. Include present, simple past, and simple future tenses."}
]

introduction_instructions = [
    {"name": "In Media Res", "age": [4, 5], "instruction": "Begin the story in the midst of an action or event. Start with a dynamic scene that immediately engages the reader. Ensure the opening sentence introduces a sense of urgency or immediacy."},
    {"name": "Direct Address", "age": [3, 4, 5], "instruction": "Start by speaking directly to the reader or a character within the story. Use second-person or a direct question to involve the reader right from the beginning."},
    {"name": "Descriptive Scene Setting", "age": [4, 5], "instruction": "Open with a vivid description of the setting or environment. Focus on sensory details to paint a clear picture and establish the mood of the story."},
    {"name": "Dialogue", "age": [3, 4, 5], "instruction": "Begin with a line of dialogue that introduces a character or a key element of the plot. Ensure the dialogue is engaging and provides insight into the story or characters."},
    {"name": "Character Introduction", "age": [3, 4, 5], "instruction": "Start by introducing the main character through a brief description or action. Highlight traits, appearance, or a notable action that sets the stage for the character’s role."},
    {"name": "Flashback", "age": [5], "instruction": "Open with a flashback that provides background information relevant to the current story. Ensure the transition to the present is clear and adds context to the current events."},
    {"name": "Question", "age": [4, 5], "instruction": "Begin with a provocative or intriguing question that piques the reader’s curiosity. The question should relate to the theme or central conflict of the story."},
    {"name": "Action Sequence", "age": [4, 5], "instruction": "Start with a high-energy action sequence that draws the reader into the story’s immediate conflict or excitement. Ensure the action is relevant to the plot or character development."},
    {"name": "Setting the Mood", "age": [4, 5], "instruction": "Open with a focus on the mood or atmosphere, using language that evokes specific emotions. This approach should establish the tone and setting for the rest of the story."},
    {"name": "Mysterious Statement", "age": [5], "instruction": "Begin with a mysterious or enigmatic statement that creates intrigue. The opening should make the reader want to learn more about the context or meaning behind the statement."},
    {"name": "Expository Information", "age": [5], "instruction": "Start with a brief overview or exposition that sets up the background or context of the story. Provide essential information needed for the reader to understand the setting or plot."},
    {"name": "Proverb or Saying", "age": [5], "instruction": "Open with a proverb or saying that relates to the theme or lesson of the story. Ensure the proverb is relevant and sets up the story’s message or moral."},
    {"name": "Character’s Inner Thoughts", "age": [5], "instruction": "Begin with a glimpse into the main character’s thoughts or feelings. Provide insight into their inner world and how it relates to the story’s events or themes."},
    {"name": "Surprise or Twist", "age": [5], "instruction": "Open with an unexpected twist or surprising element that immediately grabs attention. The twist should be relevant to the story and set up further intrigue."},
    {"name": "Future Prediction", "age": [5], "instruction": "Start with a statement or scenario that predicts future events or outcomes. Use this to foreshadow the story’s central conflict or resolution."},
    {"name": "Simple Action", "age": [0, 1, 2], "instruction": "Begin with a straightforward action that a young child can easily visualize and understand. Focus on familiar, everyday activities that set up the context for the story."},
    {"name": "Repetitive Phrase", "age": [0, 1, 2], "instruction": "Start with a phrase or sentence that repeats throughout the book. Use repetition to create a rhythm and help the child anticipate what comes next."},
    {"name": "Sensory Description", "age": [0, 1, 2], "instruction": "Open with a sensory description that engages a young child’s senses. Describe what can be seen, heard, or felt in a way that is vivid and simple."},
    {"name": "Simple Question", "age": [0, 1, 2], "instruction": "Begin with a very simple question related to the story's theme or main character. Ensure the question is easy to understand and encourages interaction."},
    {"name": "Gentle Introduction", "age": [0, 1, 2], "instruction": "Start with a soft and gentle introduction of the main character or setting. Use calming and reassuring language suitable for very young children."},
    {"name": "Interactive Prompt", "age": [0, 1, 2], "instruction": "Begin with a prompt that invites the child to participate or engage with the story. For example, ask the child to point to something or make a sound related to the story."},
    {"name": "Simple Action with Sound", "age": [0, 1, 2], "instruction": "Start with a simple action paired with a sound that can be repeated or mimicked by the child. This can be a sound effect or a noise related to the character’s actions."},
    {"name": "Familiar Routine", "age": [0, 1, 2], "instruction": "Begin by describing a familiar routine or daily activity that young children can relate to. This helps ground the story in something they experience regularly."}
]

conclusion_instructions = [
    {"name": "Resolution", "age": [3, 4, 5], "instruction": "Tie up the story's main plot points in a satisfying and meaningful way. Ensure that the resolution reflects the characters' development and is not just a quick fix. Use specific details to make it feel earned."},
    {"name": "Happy Ending", "age": [3, 4, 5], "instruction": "Conclude with a joyful and uplifting outcome that feels genuine. Avoid generic conclusions by incorporating specific achievements or celebrations that reflect the story’s unique elements."},
    {"name": "Surprise Twist", "age": [4, 5], "instruction": "Incorporate a surprising yet logical twist that fits naturally within the story. Ensure the twist is original and enhances the overall narrative without feeling forced."},
    {"name": "Moral or Lesson", "age": [4, 5], "instruction": "Integrate the lesson within the story’s events, allowing it to emerge from the characters' experiences rather than stating it explicitly. Make sure the lesson is subtle and tied to the story’s themes."},
    {"name": "Circular Ending", "age": [3, 4, 5], "instruction": "Create a sense of closure by linking the end of the story to its beginning. Introduce unique details or changes to make the circular pattern feel fresh and engaging."},
    {"name": "Open-ended", "age": [4, 5], "instruction": "Leave the story with an ending that invites curiosity and imagination. Ensure the ending provides a sense of closure while allowing for further exploration or interpretation."},
    {"name": "Character Growth", "age": [3, 4, 5], "instruction": "Showcase a meaningful transformation in the main character, reflecting their journey throughout the story. Ensure the growth feels authentic and is a natural outcome of the character’s actions."},
    {"name": "Interactive Ending", "age": [3, 4, 5], "instruction": "Engage the reader directly by prompting them to think about what might happen next or by asking questions related to the story’s themes. Ensure the interaction feels natural and relevant to the story."},
    {"name": "Simple Conclusion", "age": [0, 1, 2, 3], "instruction": "Wrap up the story with a straightforward but satisfying ending. Focus on a clear and positive resolution without unnecessary complexity, suitable for younger children."},
    {"name": "Playful Ending", "age": [0, 1, 2, 3], "instruction": "Conclude with a light-hearted and imaginative finish that captures the playful spirit of the story. Ensure the ending is creative and aligns with the whimsical elements of the narrative."},
    {"name": "Reflective Ending", "age": [4, 5], "instruction": "Conclude with a moment of reflection that encourages readers to think about the story’s themes or messages. Avoid heavy-handedness by integrating reflection naturally into the characters' experiences or dialogues."},
    {"name": "Celebratory Ending", "age": [3, 4, 5], "instruction": "End the story with a joyful celebration of a significant achievement or event. Ensure the celebration feels authentic and is integrated into the story’s conclusion. Avoid clichés by focusing on specific achievements or unique aspects of the story."},
    {"name": "Transformation Ending", "age": [4, 5], "instruction": "End with a significant physical or metaphorical transformation of the main character or key element in the story. Ensure that the transformation is meaningful and well-integrated into the story’s overall theme."},
    {"name": "Nostalgic Ending", "age": [4, 5], "instruction": "Wrap up the story with a sense of longing or reflection on the past. Emphasize the fond memories or past experiences of the characters. Ensure that the nostalgia is conveyed through subtle, heartfelt moments rather than overt sentimentality."},
    {"name": "Return to Normalcy", "age": [3, 4, 5], "instruction": "Conclude with the characters returning to their previous state or routine after experiencing a significant event or adventure. Emphasize the comfort and stability of returning to familiar patterns. Avoid making the return feel anticlimactic by maintaining relevance to the story’s main themes."},
    {"name": "Interactive Ending", "age": [3, 4, 5], "instruction": "End the story with a prompt or question that engages the reader directly, inviting them to think or respond. Ensure the interactive element is naturally integrated into the narrative and ties back to the story’s themes or messages."}
]